import type { SubjectInfo, Badge, PlayerProgress, BuddyCharacter } from './types';

export const XP_PER_LEVEL = 100;
export const XP_PER_CORRECT = 10;
export const XP_PER_GAME = 5;
export const STREAK_BONUS = 20;

export const SUBJECTS: SubjectInfo[] = [
  { id: 'chinese', name: 'Chinese 中文', icon: '📝', color: '#ef4444', gradient: 'from-red-500 to-rose-600' },
  { id: 'english', name: 'English', icon: '🔤', color: '#3b82f6', gradient: 'from-blue-500 to-indigo-600' },
  { id: 'maths', name: 'Maths 數學', icon: '🔢', color: '#22c55e', gradient: 'from-green-500 to-emerald-600' },
  { id: 'general-studies', name: 'General Studies 常識', icon: '🌍', color: '#f59e0b', gradient: 'from-amber-500 to-yellow-600' },
  { id: 'science', name: 'Science 科學', icon: '🔬', color: '#06b6d4', gradient: 'from-cyan-500 to-teal-600' },
  { id: 'music', name: 'Music 音樂', icon: '🎵', color: '#d946ef', gradient: 'from-fuchsia-500 to-pink-600' },
  { id: 'visual-arts', name: 'Visual Arts 視藝', icon: '🎨', color: '#f97316', gradient: 'from-orange-500 to-red-500' },
  { id: 'pe', name: 'PE 體育', icon: '⚽', color: '#84cc16', gradient: 'from-lime-500 to-green-600' },
  { id: 'computer', name: 'Computer 電腦', icon: '💻', color: '#6366f1', gradient: 'from-indigo-500 to-violet-600' },
  { id: 'putonghua', name: 'Putonghua 普通話', icon: '🗣️', color: '#ec4899', gradient: 'from-pink-500 to-rose-600' },
  { id: 'religious-studies', name: 'Religious Studies 宗教', icon: '🕊️', color: '#a78bfa', gradient: 'from-violet-400 to-purple-600' },
  { id: 'moral-civic', name: 'Moral & Civic 德育', icon: '🤝', color: '#14b8a6', gradient: 'from-teal-500 to-cyan-600' },
  { id: 'reading', name: 'Reading 閱讀', icon: '📚', color: '#8b5cf6', gradient: 'from-purple-500 to-indigo-600' },
  { id: 'stem', name: 'STEM', icon: '🤖', color: '#0ea5e9', gradient: 'from-sky-500 to-blue-600' },
  { id: 'drama', name: 'Drama 戲劇', icon: '🎭', color: '#e11d48', gradient: 'from-rose-500 to-pink-600' },
  { id: 'social-studies', name: 'Social Studies 社會', icon: '🏛️', color: '#64748b', gradient: 'from-slate-500 to-gray-600' },
  { id: 'life-wide-learning', name: 'Life-wide Learning 全方位學習', icon: '🌱', color: '#10b981', gradient: 'from-emerald-500 to-green-600' },
];

export const GRADES = ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'] as const;

export const GAMES = [
  { id: 'quiz-battle' as const, name: 'Quiz Battle', icon: '⚔️', description: 'Answer questions to earn points!', gradient: 'from-purple-600 to-indigo-700' },
  { id: 'memory-match' as const, name: 'Memory Match', icon: '🧠', description: 'Match pairs to test your memory!', gradient: 'from-pink-600 to-rose-700' },
  { id: 'word-scramble' as const, name: 'Word Scramble', icon: '🔀', description: 'Unscramble the letters!', gradient: 'from-amber-600 to-orange-700' },
  { id: 'speed-challenge' as const, name: 'Speed Challenge', icon: '⚡', description: 'Race against the clock!', gradient: 'from-cyan-600 to-blue-700' },
  { id: 'flashcard-flip' as const, name: 'Flashcard Flip', icon: '🃏', description: 'Flip cards to learn!', gradient: 'from-emerald-600 to-teal-700' },
];

export const ALL_BADGES: Badge[] = [
  { id: 'first-game', name: 'First Steps', description: 'Play your first game', icon: '🎯', requirement: (p: PlayerProgress) => p.totalGamesPlayed >= 1 },
  { id: 'five-games', name: 'Getting Started', description: 'Play 5 games', icon: '🌟', requirement: (p: PlayerProgress) => p.totalGamesPlayed >= 5 },
  { id: 'ten-games', name: 'Game Master', description: 'Play 10 games', icon: '👑', requirement: (p: PlayerProgress) => p.totalGamesPlayed >= 10 },
  { id: 'fifty-games', name: 'Legend', description: 'Play 50 games', icon: '🏆', requirement: (p: PlayerProgress) => p.totalGamesPlayed >= 50 },
  { id: 'perfect-score', name: 'Perfect!', description: 'Get 100% in a game', icon: '💯', requirement: () => false },
  { id: 'streak-3', name: 'On Fire', description: '3-day streak', icon: '🔥', requirement: (p: PlayerProgress) => p.streak >= 3 },
  { id: 'streak-7', name: 'Unstoppable', description: '7-day streak', icon: '⚡', requirement: (p: PlayerProgress) => p.streak >= 7 },
  { id: 'level-5', name: 'Rising Star', description: 'Reach Level 5', icon: '⭐', requirement: (p: PlayerProgress) => p.level >= 5 },
  { id: 'level-10', name: 'Superstar', description: 'Reach Level 10', icon: '🌠', requirement: (p: PlayerProgress) => p.level >= 10 },
  { id: 'all-subjects', name: 'Explorer', description: 'Try all subjects', icon: '🧭', requirement: (p: PlayerProgress) => Object.values(p.subjectScores).filter(s => s.gamesPlayed > 0).length >= 5 },
  { id: 'maths-master', name: 'Maths Whiz', description: 'Play 10 maths games', icon: '🧮', requirement: (p: PlayerProgress) => (p.subjectScores['maths']?.gamesPlayed ?? 0) >= 10 },
  { id: 'english-master', name: 'Word Smith', description: 'Play 10 English games', icon: '📖', requirement: (p: PlayerProgress) => (p.subjectScores['english']?.gamesPlayed ?? 0) >= 10 },
  { id: 'chinese-master', name: '中文達人', description: 'Play 10 Chinese games', icon: '🏮', requirement: (p: PlayerProgress) => (p.subjectScores['chinese']?.gamesPlayed ?? 0) >= 10 },
  { id: 'science-master', name: 'Scientist', description: 'Play 10 Science games', icon: '🧪', requirement: (p: PlayerProgress) => (p.subjectScores['science']?.gamesPlayed ?? 0) >= 10 },
  { id: 'speed-demon', name: 'Speed Demon', description: 'Finish a speed challenge under 30s', icon: '💨', requirement: () => false },
];

export const BUDDIES: BuddyCharacter[] = [
  {
    id: 'panda',
    name: 'Bao Bao',
    emoji: '🐼',
    personality: 'Friendly and patient — loves bamboo and learning!',
    color: '#22c55e',
    bgGradient: 'from-green-500 to-emerald-600',
    greeting: 'Hi friend! 🎋 Ready to learn something awesome today?',
    askPhrases: [
      'Hmm, let me think of a good question... 🤔',
      'Ooh ooh, try this one! 🎋',
      'Here comes a tricky one! Can you handle it? 💪',
      'I believe in you! Check this out:',
      'My bamboo brain says... try this! 🐼',
    ],
    correctReactions: [
      'AMAZING! You\'re so smart! 🎉🐼',
      'Woohoo! That\'s right! *munches bamboo happily* 🎋',
      'You got it! High five! ✋🐼',
      'Brilliant! You\'re a genius! 🌟',
      'Yes yes yes! Perfect answer! 🎊',
    ],
    wrongReactions: [
      'Oops! Don\'t worry, even pandas fall sometimes! 🐼💕',
      'Not quite, but you\'re learning! That\'s what matters! 🌱',
      'Hmm, close! Let\'s try again! 💪',
      'No worries! Every mistake makes you smarter! 🧠',
    ],
    encouragements: [
      'You\'re doing great! Keep going! 🎋',
      'I\'m so proud of you! 🐼💕',
      'Learning is fun with you! 🌟',
      'You\'re getting better every day! 📈',
    ],
  },
  {
    id: 'fox',
    name: 'Foxy',
    emoji: '🦊',
    personality: 'Clever and playful — always up for a challenge!',
    color: '#f97316',
    bgGradient: 'from-orange-500 to-red-500',
    greeting: 'Hey there, clever one! 🦊 Let\'s outsmart some questions!',
    askPhrases: [
      'My foxy senses say... try this! 🦊',
      'Ooh, this is a clever one! Ready? 🧠',
      'Let\'s see how sharp you are! 🌟',
      'Here\'s a brain teaser for you! 💡',
      'Think you can crack this? Let\'s go! 🔥',
    ],
    correctReactions: [
      'Clever as a fox! Wait... that\'s me! 🦊✨',
      'BRILLIANT! You\'re so smart! 🎉',
      'Nailed it! You\'re a genius! 🏆',
      'Wow, even I\'m impressed! 🌟',
      'That\'s the right answer! Amazing! 💯',
    ],
    wrongReactions: [
      'Tricky one, huh? Don\'t worry! 🦊💕',
      'Even foxes get tricked sometimes! Try again! 🌈',
      'So close! You\'ll get it next time! 💪',
      'That\'s okay! Learning from mistakes is super smart! 🧠',
    ],
    encouragements: [
      'You\'re as clever as a fox! 🦊',
      'Keep going, superstar! ⭐',
      'Nothing can stop you! 🔥',
      'You make learning look easy! 😎',
    ],
  },
  {
    id: 'cat',
    name: 'Miu Miu',
    emoji: '🐱',
    personality: 'Curious and sassy — purrs when you get it right!',
    color: '#d946ef',
    bgGradient: 'from-fuchsia-500 to-pink-600',
    greeting: 'Meow! 🐱 Let\'s pounce on some knowledge today!',
    askPhrases: [
      '*paws at question* What do you think? 🐾',
      'Meow! Here\'s a purr-fect question! 🐱',
      'My whiskers are tingling... try this! ✨',
      'Let\'s see if you\'re as curious as me! 🐾',
      'Here\'s something interesting... 👀',
    ],
    correctReactions: [
      'PURR-FECT! 🐱✨ *happy purring*',
      'Meow-velous! You got it right! 🎉',
      'That deserves a head bump! 🐱💕',
      'You\'re claw-some! Amazing answer! 🌟',
      'Purrrr... I knew you\'d get it! 😻',
    ],
    wrongReactions: [
      'Meow... not quite! But I still like you! 🐱💕',
      'Oops! Even cats have nine lives to try again! 🐾',
      'Don\'t worry, curiosity helps us learn! ✨',
      'Almost! Let\'s scratch at it again! 🐱',
    ],
    encouragements: [
      'You\'re purr-fectly amazing! 🐱',
      'Keep being curious! 🌟',
      'You\'re the cat\'s meow! 😸',
      'Learning looks good on you! ✨',
    ],
  },
  {
    id: 'dog',
    name: 'Buddy',
    emoji: '🐶',
    personality: 'Loyal and enthusiastic — your best study friend!',
    color: '#a78bfa',
    bgGradient: 'from-violet-400 to-purple-600',
    greeting: 'Woof woof! 🐶 I\'m SO excited to learn with you!',
    askPhrases: [
      '*tail wagging* Ooh ooh, try this! 🐶',
      'I fetched a great question for you! 🎾',
      'Woof! Here\'s a good one! 🐾',
      '*happy panting* Ready? Here we go! 🌟',
      'I dug up this question just for you! 🦴',
    ],
    correctReactions: [
      'WOOF WOOF! AMAZING! *jumps around* 🐶🎉',
      'Good human! Such a smart cookie! 🍪',
      'You deserve ALL the treats! 🦴✨',
      '*licks your face* YOU GOT IT! 🐶💕',
      'BEST. ANSWER. EVER! *tail wagging intensifies* 🌟',
    ],
    wrongReactions: [
      'That\'s okay! I still love you! 🐶💕',
      'Woof... let\'s try again together! 🐾',
      'Don\'t worry! Every good dog learns from mistakes! 🌈',
      'Almost! You\'re still my favourite human! 🐶❤️',
    ],
    encouragements: [
      'You\'re doing PAWSOME! 🐶',
      'I\'m your biggest fan! 🎉',
      'You\'re the GOODEST learner! 🌟',
      'Woof! So proud of you! 🐾',
    ],
  },
  {
    id: 'owl',
    name: 'Professor Hoot',
    emoji: '🦉',
    personality: 'Wise and calm — the smartest teacher in the forest!',
    color: '#6366f1',
    bgGradient: 'from-indigo-500 to-violet-600',
    greeting: 'Hoo-hoo! 🦉 Welcome, young scholar! Knowledge awaits!',
    askPhrases: [
      'In my years of wisdom, I present to you... 🦉',
      'A wise owl asks: can you solve this? 📚',
      'Let me share some knowledge with you... 🌙',
      'From the ancient library of wisdom... 📖',
      '*adjusts spectacles* Now then, try this! 🤓',
    ],
    correctReactions: [
      'Most excellent! You are truly wise! 🦉✨',
      'Hoo-hoo! Brilliant deduction! 🎓',
      'A scholar\'s answer indeed! Magnificent! 📚',
      'Knowledge flows through you! Well done! 🌟',
      'Wise beyond your years! Hoo-hoo! 🦉👏',
    ],
    wrongReactions: [
      'Even the wisest owl must learn... try again! 🦉📚',
      'A valuable lesson! Mistakes are teachers too! 🌙',
      'Hoo... not quite, but wisdom comes with practice! 🌟',
      'The path to knowledge has many turns! Keep going! 🗺️',
    ],
    encouragements: [
      'Your wisdom grows with each question! 🦉',
      'A true scholar never stops learning! 📚',
      'Hoo-hoo! Magnificent progress! 🌟',
      'The forest is proud of you! 🌲',
    ],
  },
  {
    id: 'rabbit',
    name: 'Bunny',
    emoji: '🐰',
    personality: 'Quick and bubbly — hops with joy when you learn!',
    color: '#ec4899',
    bgGradient: 'from-pink-500 to-rose-600',
    greeting: 'Hop hop! 🐰 Let\'s bounce through some fun questions!',
    askPhrases: [
      '*hops excitedly* Try this one! 🐰',
      'Quick quick! Here\'s a question! 🥕',
      'I hopped all the way here with this! 🐾',
      'My bunny brain has a question! 🌸',
      'Hop to it! Ready? 🐰✨',
    ],
    correctReactions: [
      'HOP HOP HOORAY! You got it! 🐰🎉',
      'Ear-resistible answer! Amazing! 🐰✨',
      '*happy bunny dance* CORRECT! 💃🐰',
      'You\'re hopping amazing! 🌟',
      'Carrot-tastic answer! Well done! 🥕🎊',
    ],
    wrongReactions: [
      'Oopsie daisies! Let\'s hop and try again! 🐰🌼',
      'Don\'t worry, little one! Bunnies bounce back! 💕',
      'Almost there! One more hop! 🐰',
      'That\'s okay! Every bunny makes mistakes! 🌈',
    ],
    encouragements: [
      'Keep hopping along! You\'re doing great! 🐰',
      'Somebunny is super smart! 🌟',
      'Hop hop hop to success! 🎉',
      'You make my cotton tail wiggle with pride! 🐰💕',
    ],
  },
  {
    id: 'dragon',
    name: 'Long Long',
    emoji: '🐲',
    personality: 'Brave and mighty — breathes fire when excited!',
    color: '#ef4444',
    bgGradient: 'from-red-500 to-orange-600',
    greeting: 'Roar! 🐲 The dragon of knowledge is here! Let\'s conquer!',
    askPhrases: [
      '*breathes a little fire* Here\'s a challenge! 🔥',
      'A dragon\'s riddle for you, brave one! 🐲',
      'Can you be as brave as a dragon? Try this! ⚔️',
      'From my treasure hoard of knowledge... 💎',
      'The dragon challenges you! Ready? 🐲🔥',
    ],
    correctReactions: [
      'ROAR! MAGNIFICENT! Fire of knowledge burns bright! 🐲🔥',
      'A true dragon warrior! Well done! ⚔️✨',
      'You\'ve earned a dragon\'s respect! 🐲👑',
      'LEGENDARY answer! *flies in celebration* 🎉',
      'The dragon is impressed! Most worthy! 🏆🐲',
    ],
    wrongReactions: [
      'Even dragon knights fall... but they rise again! 🐲💪',
      'A small stumble on the quest! Onward! ⚔️',
      'The dragon believes in you! Try once more! 🔥',
      'Every hero learns from battles! Keep going! 🛡️',
    ],
    encouragements: [
      'Your courage is legendary! 🐲⚔️',
      'The dragon flies beside you! 🔥',
      'A true champion of knowledge! 🏆',
      'Roar with pride! You\'re amazing! 🐲',
    ],
  },
  {
    id: 'unicorn',
    name: 'Starlight',
    emoji: '🦄',
    personality: 'Magical and sparkly — sprinkles magic dust on learning!',
    color: '#a855f7',
    bgGradient: 'from-purple-500 to-pink-500',
    greeting: 'Sparkle sparkle! 🦄✨ Let\'s make some magic today!',
    askPhrases: [
      '*sprinkles magic dust* Here\'s a magical question! ✨',
      'My horn is glowing! That means... question time! 🦄',
      'From the enchanted forest of knowledge... 🌈',
      'A magical mystery for you! 💫',
      'Let\'s see some sparkly brainpower! ✨🧠',
    ],
    correctReactions: [
      'MAGICAL! ✨ You\'re absolutely enchanting! 🦄🎉',
      'Sparkle sparkle! CORRECT! *rainbow appears* 🌈',
      'You\'re more magical than a unicorn! Wait... 🦄😄',
      'DAZZLING answer! Pure magic! ✨💯',
      'The stars are shining for you! 🌟🦄',
    ],
    wrongReactions: [
      'Even magic takes practice! Try again! 🦄💕',
      'Sprinkle some more magic dust and retry! ✨',
      'The rainbow is still shining for you! 🌈',
      'Don\'t worry! You\'re still magical! 🦄💫',
    ],
    encouragements: [
      'You\'re truly magical! ✨',
      'Sparkle on, superstar! 🦄🌟',
      'The whole rainbow believes in you! 🌈',
      'You make the world more magical! 💫',
    ],
  },
  {
    id: 'penguin',
    name: 'Waddles',
    emoji: '🐧',
    personality: 'Cool and chill — slides through problems with ease!',
    color: '#0ea5e9',
    bgGradient: 'from-sky-500 to-blue-600',
    greeting: 'Hey cool cat! 🐧 Let\'s slide into some learning!',
    askPhrases: [
      '*slides over* Got a cool question for you! 🐧',
      'Chill out and try this one! ❄️',
      'Ice ice baby! Here\'s a question! 🧊',
      'From the South Pole of knowledge... 🌊',
      'Waddle waddle... question time! 🐧',
    ],
    correctReactions: [
      'ICE COLD! That answer was PERFECT! 🐧❄️',
      'You\'re cooler than Antarctica! Amazing! 🎉',
      '*happy waddle dance* CORRECT! 🐧💃',
      'That was so smooth! Like sliding on ice! ✨',
      'Penguin approved! Top marks! 🏆🐧',
    ],
    wrongReactions: [
      'Whoops! Slippery question! Try again! 🐧💕',
      'Even penguins slip sometimes! No worries! ❄️',
      'Chill, you\'ll get it next time! 🌊',
      'Just a little slide! Waddle back up! 🐧',
    ],
    encouragements: [
      'Stay cool, you\'re doing great! 🐧',
      'Smooth sailing from here! 🌊',
      'You\'re the coolest learner ever! ❄️',
      'Ice-credible progress! Keep going! 🐧✨',
    ],
  },
  {
    id: 'bear',
    name: 'Honey',
    emoji: '🐻',
    personality: 'Warm and cuddly — gives bear hugs for correct answers!',
    color: '#b45309',
    bgGradient: 'from-amber-700 to-yellow-600',
    greeting: 'Bear hug! 🐻 Let\'s have a honey-sweet study session!',
    askPhrases: [
      '*bear stretch* Ready for this one? 🐻',
      'Honey, try this sweet question! 🍯',
      'My bear instincts say... question time! 🐻',
      'Rawr! Here comes a good one! 💪',
      'From my cozy cave of knowledge... 🏔️',
    ],
    correctReactions: [
      'BEAR HUG! You got it right! 🐻🤗',
      'Sweet as honey! Perfect answer! 🍯✨',
      'You\'re un-BEAR-ably smart! 🐻🎉',
      'That answer is grizzly good! 🏆',
      '*biggest bear hug ever* AMAZING! 🐻💕',
    ],
    wrongReactions: [
      'Aw, that\'s okay! Bear hug! 🐻💕',
      'Don\'t hibernate on this — try again! 🐻',
      'Even the biggest bears stumble! 🌈',
      'Shake it off and try once more! 💪🐻',
    ],
    encouragements: [
      'You\'re doing bear-y well! 🐻',
      'Keep going, honey! 🍯',
      'The forest is cheering for you! 🌲',
      'Strong and smart — just like a bear! 💪',
    ],
  },
  {
    id: 'monkey',
    name: 'Kiki',
    emoji: '🐵',
    personality: 'Cheeky and fun — always monkeying around with ideas!',
    color: '#ca8a04',
    bgGradient: 'from-yellow-600 to-amber-700',
    greeting: 'Ooh ooh ahh ahh! 🐵 Let\'s swing through some questions!',
    askPhrases: [
      '*swings from vine* Catch this question! 🐵',
      'Ooh ooh! Try this banana brain teaser! 🍌',
      'My monkey mind thought of this! 🐒',
      'Swing into action! Here\'s a question! 🌴',
      '*does a flip* Ready? Here we go! 🐵',
    ],
    correctReactions: [
      'OOH OOH AHH AHH! CORRECT! 🐵🎉',
      'You\'re going bananas with those right answers! 🍌✨',
      'Monkey see, monkey do — and you DID IT! 🐒🏆',
      '*swings with joy* AMAZING! 🐵💯',
      'Top of the tree! Best answer ever! 🌴⭐',
    ],
    wrongReactions: [
      'Oops! Even monkeys drop bananas! 🐵🍌',
      'Don\'t monkey around — focus and try again! 💪',
      'Swing back and have another go! 🌴',
      'That\'s okay, cheeky one! Next time! 🐵💕',
    ],
    encouragements: [
      'You\'re swinging through this! 🐵',
      'Go bananas with learning! 🍌',
      'The jungle is proud of you! 🌴',
      'Monkeying around and learning! Best combo! 🐒✨',
    ],
  },
  {
    id: 'koala',
    name: 'Sleepy',
    emoji: '🐨',
    personality: 'Relaxed and wise — takes things one leaf at a time!',
    color: '#6b7280',
    bgGradient: 'from-gray-500 to-slate-600',
    greeting: '*yawn* 🐨 Oh hey! Ready for some chill learning?',
    askPhrases: [
      '*stretches* Here\'s a cozy question... 🐨',
      'No rush, take your time with this one! 🌿',
      'From my eucalyptus tree of wisdom... 🍃',
      '*blinks sleepily* Try this! 🐨',
      'Easy does it... here\'s a question! ☁️',
    ],
    correctReactions: [
      '*wakes up* Whoa! You got it RIGHT! 🐨🎉',
      'Koala-ty answer! Well done! 🐨✨',
      'Even I\'m impressed — and I\'m hard to impress! 🌟',
      'That was tree-mendous! 🌿🏆',
      '*happy koala noises* Perfect! 🐨💯',
    ],
    wrongReactions: [
      '*cuddles you* It\'s okay! Try again! 🐨💕',
      'No stress! Take a breather and retry! 🌿',
      'Even koalas fall from trees sometimes! 🐨',
      'Slow and steady wins the race! 🌈',
    ],
    encouragements: [
      'You\'re doing koala-ty work! 🐨',
      'Chill and learn — you\'ve got this! 🌿',
      'Slow and steady! Keep going! 🐨',
      'The eucalyptus trees applaud you! 🍃',
    ],
  },
  {
    id: 'dolphin',
    name: 'Splash',
    emoji: '🐬',
    personality: 'Playful and brilliant — the smartest in the sea!',
    color: '#0891b2',
    bgGradient: 'from-cyan-600 to-teal-600',
    greeting: 'Eee-eee! 🐬 Dive into learning with me!',
    askPhrases: [
      '*does a flip* Here\'s a splashing question! 🐬',
      'Deep dive time! Try this! 🌊',
      'From the ocean of knowledge... 🐬',
      '*clicks happily* Question incoming! 💧',
      'Ride the wave of this question! 🌊',
    ],
    correctReactions: [
      'SPLASH! That was PERFECT! 🐬🎉',
      'You\'re making waves of awesomeness! 🌊✨',
      'Fin-tastic answer! Dolphin approved! 🐬🏆',
      '*leaps out of water in joy* AMAZING! 💦',
      'Ocean-level genius right there! 🌊💯',
    ],
    wrongReactions: [
      'Dive back in and try again! 🐬💕',
      'The ocean has many answers — keep swimming! 🌊',
      'Even dolphins need practice! You\'ve got this! 🐬',
      'Ride the next wave — you\'ll get it! 🌊',
    ],
    encouragements: [
      'You\'re swimming along beautifully! 🐬',
      'Making a splash in learning! 🌊',
      'Fin-credible progress! 🐬✨',
      'The whole ocean is cheering for you! 🌊',
    ],
  },
  {
    id: 'hamster',
    name: 'Cheeks',
    emoji: '🐹',
    personality: 'Tiny but mighty — stores knowledge like sunflower seeds!',
    color: '#f59e0b',
    bgGradient: 'from-amber-500 to-orange-500',
    greeting: 'Squeak squeak! 🐹 Let\'s fill our brains with knowledge!',
    askPhrases: [
      '*stuffs cheeks* Ooh try this one! 🐹',
      'My tiny paws found a big question! 🌻',
      'Squeak! Here\'s a nutty question! 🥜',
      'Running on my wheel of knowledge... 🐹',
      'Small but mighty question coming! 💪',
    ],
    correctReactions: [
      'SQUEAK! You\'re SO SMART! 🐹🎉',
      '*does a happy wheel spin* CORRECT! ✨',
      'Storing that in my cheeks! Great answer! 🐹💯',
      'Sunflower seed worthy answer! 🌻🏆',
      'My little heart is so proud! 🐹💕',
    ],
    wrongReactions: [
      'Squeak... that\'s okay tiny friend! 🐹💕',
      'Even hamsters drop seeds! Try again! 🌻',
      'Spin the wheel once more! 🐹',
      'Tiny steps lead to big learning! 💪',
    ],
    encouragements: [
      'You\'re hamster-iffic! 🐹',
      'Small steps, big brain! 🌻',
      'Keep running that knowledge wheel! 🐹',
      'The cutest learner ever! 💕',
    ],
  },
  {
    id: 'tiger',
    name: 'Stripes',
    emoji: '🐯',
    personality: 'Fierce and focused — pounces on problems with power!',
    color: '#ea580c',
    bgGradient: 'from-orange-600 to-red-600',
    greeting: 'GRRRR! 🐯 The tiger of learning is ready to pounce!',
    askPhrases: [
      '*crouches low* Ready to pounce on this? 🐯',
      'The tiger stalks... a wild question appears! 🌿',
      'Show me your stripes! Try this! 🐯',
      'Fierce focus time! Here we go! 🔥',
      '*tail swishes* Challenge accepted? 🐯',
    ],
    correctReactions: [
      'ROAR! You CRUSHED it! 🐯🔥',
      'Tiger-ific! What a powerful answer! 🐯🏆',
      'You\'ve earned your stripes! AMAZING! ⚡✨',
      '*victory roar* THAT WAS INCREDIBLE! 🐯🎉',
      'Fierce AND smart! Unbeatable combo! 💯🐯',
    ],
    wrongReactions: [
      'Every tiger misses sometimes! Pounce again! 🐯💪',
      'Sharpen those claws and try once more! 🐯',
      'The jungle cheers for those who try! 🌿',
      'Stay fierce! You\'ll get it! 🐯🔥',
    ],
    encouragements: [
      'Tiger-strong learning! 🐯',
      'You\'re the fiercest learner! 🔥',
      'Earning your stripes every day! 🐯',
      'The jungle bows to your power! 🌿👑',
    ],
  },
  {
    id: 'butterfly',
    name: 'Flutter',
    emoji: '🦋',
    personality: 'Gentle and free — transforms learning into something beautiful!',
    color: '#8b5cf6',
    bgGradient: 'from-violet-500 to-purple-600',
    greeting: 'Flutter flutter! 🦋 Let\'s transform our minds today!',
    askPhrases: [
      '*lands softly* Here\'s a beautiful question! 🦋',
      'Let your mind take flight with this! 🌸',
      'A question as pretty as a flower! 🌺',
      'Spread your wings and try this! 🦋',
      'From garden to garden... question time! 🌷',
    ],
    correctReactions: [
      'BEAUTIFUL! You\'re blossoming! 🦋🌸',
      'Your brain is spreading its wings! 🦋✨',
      'Pretty and smart — what a combo! 🌺🎉',
      'A perfect metamorphosis of an answer! 🦋💯',
      'You\'re SOARING! Magnificent! 🦋🏆',
    ],
    wrongReactions: [
      'Every caterpillar becomes a butterfly! Keep going! 🦋💕',
      'Gentle wings try again! You\'ll fly! 🌸',
      'The garden still blooms for you! 🌺',
      'Transform that answer — try once more! 🦋',
    ],
    encouragements: [
      'You\'re transforming beautifully! 🦋',
      'Spread those learning wings! 🌸',
      'Fluttering through with grace! 🦋',
      'The whole garden cheers for you! 🌺✨',
    ],
  },
];